export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CREATE_ORDER = "CREATE_ORDER"
export const CLEAR_ORDER = "CLEAR_ORDER"
export const CLEAR_CART = "CLEAR_CART"
